#!/usr/bin/env bash

# Update the package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Start nginx
sudo /etc/init.d/nginx start

# Configure nginx to listen on port 80
sudo sed -i 's/listen\ 80;/listen\ 80\ default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo /etc/init.d/nginx restart

# Create a new index.html file with the "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html
