#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /hello {
        return 200 "Hello World!";
    }
}
EOF
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
