#!/usr/bin/env bash
# Install nginx on your web-01 server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "s/# server_name_/rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n# server_name_/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "s/# server_name_/error_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\treturn 404 \"Ceci n'est pas une page\";\n\t}\n\n# server_name_/" /etc/nginx/sites-available/default
service nginx restart
